# Generated by Django 3.1.3 on 2021-07-05 12:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='treatment',
            name='ImageLink',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='patientfile',
            name='Date',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 5, 18, 15, 53, 339003)),
        ),
        migrations.AlterField(
            model_name='patientrecord',
            name='Date',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 5, 18, 15, 53, 337999)),
        ),
    ]
