# Generated by Django 3.2.8 on 2021-11-10 04:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faq',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='patientfile',
            name='Date',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 10, 9, 56, 53, 654793)),
        ),
        migrations.AlterField(
            model_name='patientfile',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='patientrecord',
            name='Date',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 10, 9, 56, 53, 654793)),
        ),
        migrations.AlterField(
            model_name='patientrecord',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
