# Generated by Django 3.2.8 on 2021-10-17 16:51

import database.models
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('Address', models.TextField(blank=True, null=True)),
                ('Age', models.IntegerField(blank=True, null=True)),
                ('Gender', models.CharField(blank=True, max_length=6, null=True)),
                ('password', models.CharField(editable=False, max_length=100)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Day',
            fields=[
                ('Date', models.DateField(default=database.models.datetime_date, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Question', models.TextField()),
                ('Answer', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Package',
            fields=[
                ('Price', models.IntegerField(primary_key=True, serialize=False)),
                ('Duration', models.CharField(max_length=10)),
                ('Description', models.TextField(max_length=100)),
                ('PaymentLink', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='PatientTreatment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField(default=database.models.datetime_date)),
                ('Validity', models.CharField(max_length=10)),
                ('ClosedStatus', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Treatment',
            fields=[
                ('Name', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('Description', models.TextField()),
                ('ImageLink', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('User', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='database.user')),
                ('PatientVerified', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Slot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TimeAlloted', models.TimeField(default=database.models.datetime_time)),
                ('Description', models.TextField(blank=True, null=True)),
                ('PaymentMade', models.BooleanField(default=False)),
                ('PaymentReceipt', models.TextField(blank=True, null=True)),
                ('DateAlloted', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='DateAlloted', to='database.day')),
                ('Package', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Package', to='database.package')),
                ('PatientTreatment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='PatientTreatment', to='database.patienttreatment')),
            ],
        ),
        migrations.AddField(
            model_name='patienttreatment',
            name='Treatment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Treatment', to='database.treatment'),
        ),
        migrations.CreateModel(
            name='PatientRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateTimeField(default=database.models.datetime_now)),
                ('Report', models.TextField()),
                ('PatientTreatment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.patienttreatment')),
            ],
        ),
        migrations.CreateModel(
            name='PatientFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(blank=True, max_length=50, null=True)),
                ('Date', models.DateTimeField(default=database.models.datetime_now)),
                ('File', models.FileField(upload_to='patientfiles/')),
                ('PatientTreatment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.patienttreatment')),
            ],
        ),
        migrations.AddField(
            model_name='patienttreatment',
            name='Patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.patient'),
        ),
    ]
