# Generated by Django 3.2.8 on 2021-10-18 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='PaymentLink',
            field=models.CharField(max_length=50),
        ),
    ]
