# Generated by Django 3.2.4 on 2021-07-05 15:44

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Day',
            fields=[
                ('Date', models.DateField(default=datetime.date(2021, 7, 5), primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Slot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TimeAlloted', models.TimeField(default=datetime.time(21, 14, 57, 686089))),
                ('Description', models.TextField(blank=True, null=True)),
                ('DateAlloted', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='consultation.day')),
            ],
        ),
    ]
