# Generated by Django 3.1.3 on 2021-08-08 05:34

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Day',
            fields=[
                ('Date', models.DateField(default=datetime.date(2021, 8, 8), primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Slot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TimeAlloted', models.TimeField(default=datetime.time(11, 4, 27, 314280))),
                ('Description', models.TextField(blank=True, null=True)),
                ('DateAlloted', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='DateAlloted', to='consultation.day')),
            ],
        ),
    ]
