# Generated by Django 3.1.3 on 2021-06-13 06:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '0001_initial'),
        ('consultation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='slot',
            name='Patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.patient'),
        ),
    ]
