# Generated by Django 3.2.8 on 2021-11-10 04:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultation', '0002_auto_20210808_1323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='day',
            name='Date',
            field=models.DateField(default=datetime.date(2021, 11, 10), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='slot',
            name='TimeAlloted',
            field=models.TimeField(default=datetime.time(9, 56, 53, 670418)),
        ),
        migrations.AlterField(
            model_name='slot',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
